### ISSUE TITLE
Writeup .pdf in git repo

### ISSUE THREAD

**Issue by kwshi** [redpanda1234/barnes-rust#17]
Git repos are meant primarily for source code; storing binary PDFs in git repos is not very great >:(.

*Consider* building your `.tex` with Travis-CI and offloading these files to a website for a more *user-friendly* experience.

Also, your write-up currently lacks substance and is a little boring to read.

**Comment by redpanda1234** [comment]
thanks kye.

**Comment by redpanda1234** [comment]
Harry doesn't have a TeX distribution installed, so he can only interact with our writeup by having me build it and then push the changes.

**Comment by redpanda1234** [comment]
unlucky
